### ISSUE TITLE
500 Errors and no communication with Bybit

### ISSUE THREAD

**Issue by bhsatterwhite1** [Mtemi/Bybit-Auto-Trading-Bot-Ordes-placed-via-TradingView-Webhook#17]
I went as far as I can but seem to be stuck at the moment.

Everything is installed. The bot python is running. Ngrok is running and we are getting data in from the tradingview webhook every minute. I'm still not getting any activity to or from Bybit. 

I'm running all of this on a Raspberry Pi 4 8 GB ram running the latest Ubuntu OS. I'm working to set this up on the Bybit test net if that is relevant.

See the replies from the terminal below.

127.0.0.1 - - [18/Jul/2021 01:05:40] "POST /webhook HTTP/1.1" 500 -
Data as Literal {'type': 'market', 'side': 'buy', 'amount': '0.01', 'symbol': 'ETHUSD', 'key': 'bf110da8a214b863838dad8c7e1f0d4609a356a8460803dc6e14a2c1'}
Data Read From File {'type': 'Market', 'side': 'Buy', 'amount': '0.01', 'symbol': 'ETHUSD', 'takeProfit': '5', 'stopLoss': '1', 'trailingStop': '0', 'leverage': '25', 'key': 'bf110da8a214b863838dad8c7e1f0d4609a356a8460803dc6e14a2c1'}
Updated Data {'type': 'market', 'side': 'buy', 'amount': '0.01', 'symbol': 'ETHUSD', 'takeProfit': '5', 'stopLoss': '1', 'trailingStop': '0', 'leverage': '25', 'key': 'bf110da8a214b863838dad8c7e1f0d4609a356a8460803dc6e14a2c1'}
{'type': 'market', 'side': 'buy', 'amount': '0.01', 'symbol': 'ETHUSD', 'takeProfit': '5', 'stopLoss': '1', 'trailingStop': '0', 'leverage': '25', 'key': 'bf110da8a214b863838dad8c7e1f0d4609a356a8460803dc6e14a2c1'}
 [Alert Received] 
POST Received/Updated Data: {'type': 'market', 'side': 'buy', 'amount': '0.01', 'symbol': 'ETHUSD', 'takeProfit': '5', 'stopLoss': '1', 'trailingStop': '0', 'leverage': '25', 'key': 'bf110da8a214b863838dad8c7e1f0d4609a356a8460803dc6e14a2c1'}
Sending: ETHUSD market buy 0.01
Trading Amount: 0.01
Side: buy
Type: market
Wallet Balance ----------------------------------------------------------
Wallet Balance------------------------------------------------(((( {'ret_code': 10003, 'ret_msg': 'invalid api_key', 'ext_code': '', 'ext_info': '', 'result': None, 'time_now': '1626588347.491405'}
[2021-07-18 01:05:47,650] ERROR in app: Exception on /webhook [POST]
Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/Bot-QKn0Xe1W/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/share/virtualenvs/Bot-QKn0Xe1W/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/share/virtualenvs/Bot-QKn0Xe1W/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/share/virtualenvs/Bot-QKn0Xe1W/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/pi/Bot/webhook-bot.py", line 50, in webhook
    send_order(datas)
  File "/home/pi/Bot/actions.py", line 90, in send_order
    print(wallet_balance['result']['BTC']['available_balance'])
TypeError: 'NoneType' object is not subscriptable
127.0.0.1 - - [18/Jul/2021 01:05:47] "POST /webhook HTTP/1.1" 500 -
^C(Bot-QKn0Xe1W) pi@pi-desktop:~/Bot$

**Comment by Mtemi** [comment]
I see by first instance that you have an error with your Bybit API keys. Get proper Bybit API keys and insert the keys at the code instances where required. There could be more than one instance to update your API keys on the code.

**Comment by Mtemi** [comment]
The code again is a bit basic , as you can see there are no try catch for exceptions emerging from various executions

**Comment by Mtemi** [comment]
line 13 and 78 of actions.py you can set parameter test = True or False depends on whether you want use testnet or actual keys:  

bybit1 = Bybit(api_key="dgregeGSlrwefwvwwe1",
                 secret="gwgwwegweBI2eefeqwfweqtX", symbol=data['symbol'], ws=True, test=False)

set the parameter accordingly
