### ISSUE TITLE
syntax error in actions.py

### ISSUE THREAD

**Issue by kitt-th** [Mtemi/Bybit-Auto-Trading-Bot-Ordes-placed-via-TradingView-Webhook#4]
Looks like it's missing the logical operator _and_ between `position_side == 'None'`  and `data['stopLoss']!='None'`

`Traceback (most recent call last):
  File "webhook-bot.py", line 9, in <module>
    from actions import send_order, parse_webhook, parse__price_webhook
  File "/Users/brian/bots/python/webhook/webhook_bot_master/actions.py", line 2179
    if position_side == 'None' data['stopLoss']!='None' and data['trailingStop']!='None':  
                                  ^
SyntaxError: invalid syntax
`

**Comment by Mtemi** [comment]
if position_side == 'None' and data['stopLoss']!='None' and data['trailingStop']!='None':

make it like above
