### ISSUE TITLE
Security Data Issues - Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [Mtemi/Bybit-Auto-Trading-Bot-Ordes-placed-via-TradingView-Webhook#5]
BITTREX_API_SECRET in clear text

Hi ,

url : https://github.com/Mtemi/Bybit-Auto-Trading-Bot-Ordes-placed-via-TradingView-Webhook/blob/915492c4b021f1f814a1bf6dbae8631931d77164/config.env

![image](https://user-images.githubusercontent.com/46863888/103934300-6c764300-512d-11eb-920c-dac5b85be406.png)

Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕

**Comment by Mtemi** [comment]
Thanks bro. Nevermind. It's non existent. This is actually a Bybit Bot. Not Bitmex
