### ISSUE TITLE
error in actions.py, line 2179

### ISSUE THREAD

**Issue by pippopippo69** [Mtemi/Bybit-Auto-Trading-Bot-Ordes-placed-via-TradingView-Webhook#6]
could you check actions.py, line 2179 ?

File "/root/inthemiddle/Bybit-Auto-Trading-Bot-Ordes-placed-via-TradingView-Webhook/actions.py", line 2179
    if position_side == 'None' data['stopLoss']!='None' and data['trailingStop']!='None':  

tks,

pippo

**Comment by Mtemi** [comment]
if position_side == 'None' and data['stopLoss']!='None' and data['trailingStop']!='None':

**Comment by pippopippo69** [comment]
ok, perfect. tks
